# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Jekyll Metro'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              'http://danielmaina.me'
baseurl:          '/metroblog'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/


# Author Details
author:         'Daniel Maina'

#Social Media links
dribbble:
email:
facebook:       
flickr:
github:         
gplus:          
instagram:
pinterest:
linkedin:       'https://fi.linkedin.com/in/danielnjuguna'
rss:
stackoverflow:
twitter:        'https://twitter.com/dan_njuguna'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: None
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: None
  twitter: https://twitter.com/dan_njuguna
  stackoverflow: #""

# Disqus
disqushandler: 'Danielm'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.8
