# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Daniel Maina'
tagline:          'The meeting-point between my work and passions'
description:      'A blog about my work and other topics of interest.'
url:              'http://localhost:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/


# Author Details
author:         'Daniel Maina'

#Social Media links
linkedin:       'https://fi.linkedin.com/in/danielnjuguna'
twitter:        'https://twitter.com/dan_maina'


# Google Analytics
gahandler: 'UA-63108237-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: fofungi@aol.com
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: links # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: 
  twitter: 
  stackoverflow: 

# Disqus
disqushandler: 'Danielm'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.8
